### ISSUE TITLE
Create the EditPictureActivity

### ISSUE THREAD

**Issue by derekdowling** [cs301w01/Skindex#24]
Create a viewPhoto screen for editing meta data with place holders for name, tags, date, album.

**Comment by BlakeBouchard** [comment]
Minus name, since individual pictures shouldn't have their own names.

**Comment by BlakeBouchard** [comment]
I'm designing the EditPicture activity to extract a Picture (currently called Photo) object reference as part of the Extras Bundle in the Intent. So when someone wants to start the EditPictureActivity, they need to pass a reference to that Picture's object as part of the Intent.
