### ISSUE TITLE
Refactoring - Simplify On Create

### ISSUE THREAD

**Issue by joelburford** [cs301w01/Skindex#80]
In the activities simplify the onCreate method.  Call a method to create listeners, etc.

**Comment by joelburford** [comment]
As an example, I did this in the EditPictureActivity class already.  Now the onCreate() calls two methods: populateTextFields() and createListeners().  The buttons logic isn't functional, but hey!

**Comment by joelburford** [comment]
Perhaps instead of populateTextFields() we should actually start implementing an "update" function in each activity that takes data and populates the onscreen fields with it.

**Comment by joelburford** [comment]
Update needs to be called with a model object.  Perhaps this is why we should have Album, Tag, Picture objects, etc.  They implement FModel and when you call update you have one of those as an argument.  For instance, in the EditPictureActivity, the update method would be "update(Picture)" and it will populate the screen with data from the Picture object.  Currently this info is stored in the PhotoManager class but that is a controller and not a model, which is weirding me out.

**Comment by Rstuvi** [comment]
WHADDUP DONE!
