### ISSUE TITLE
Change Album Spinner

### ISSUE THREAD

**Issue by derekdowling** [cs301w01/Skindex#84]
Create a default value of "Don't Change" or something to that affect. Perhaps this will go away when the spinner becomes functional. I vote we nuke the spinner in favour of a ListView Alert box.

Bug:
The change album spinner is set to the top album by default and since we can't change it without throwing an error it puts any newly created photos in the first album you have created.

**Comment by BlakeBouchard** [comment]
It doesn't throw an error any more. I had to make a new adapter for it but it works (Mind you, it populates with some really weird looking data, but hey, it's a start).

**Comment by derekdowling** [comment]
Also works.
